version: '3.8'

services:
  solana-container:
    image: linux-ubuntu-base:0.0.1
    container_name: TradeRS-Bot
    command: ["bash", "/tradeRS_start.sh"]
    networks:
      - TradeRS-Bot-net
    env_file:
      - ../.env
    volumes:
      - ./tradeRS_start.sh:/tradeRS_start.sh
      - ../logs:/logs
    restart: always
    tty: true
    stdin_open: true
    privileged: true

networks:
  TradeRS-Bot-net:
    driver: bridge