FROM ubuntu:latest

RUN apt-get update --fix-missing -y
RUN apt-get clean && rm -rf /var/lib/apt/lists/* && apt-get update --fix-missing -y
RUN apt-get install --reinstall -y curl git bash python3 libc-dev vim gcc udev jq net-tools wget libc-bin bc

# docker build -f Dockerfile.linux-ubuntu-base -t linux-ubuntu-base:0.0.1 .